# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk15

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

# https://docs.travis-ci.com/user/database-setup/#mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cosmopo;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/database-setup/#mysql
services:
  - mysql

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
notifications:
  email: true