version: "3"

services:
  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cosmoport

  cosmoport:
    build: .
    image: image_cosmoport
    restart: always
    depends_on:
      - db
    ports:
    - 8080:8080
